version: "3.1"
services:
  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
